version: '3'
services:
    postgres11:
        image: postgis/postgis:11-3.3-alpine
        command: '-c full_page_writes=off -c fsync=off -c synchronous_commit=off'
        ports:
            - '25431:5432'
        environment:
            - PGUSER=ludpo
            - PGPASSWORD=lupdos3cRet
            - PGDATABASE=test_db
            - POSTGRES_USER=lupdo
            - POSTGRES_PASSWORD=lupdos3cRet
            - POSTGRES_DB=test_db
        volumes:
            - ./src/__tests__/data/pg11.sql:/docker-entrypoint-initdb.d/init.sql

    waitpostgres11:
        image: postgis/postgis:11-3.3-alpine
        links:
            - postgres11
        depends_on:
            - postgres11
        entrypoint:
            - bash
            - -c
            - 'until /usr/local/bin/psql postgres://lupdo:lupdos3cRet@postgres11/test_db -c "SELECT 1"; do sleep 5; done'

    postgres12:
        image: postgis/postgis:12-3.3-alpine
        command: '-c full_page_writes=off -c fsync=off -c synchronous_commit=off'
        ports:
            - '25432:5432'
        environment:
            - PGUSER=ludpo
            - PGPASSWORD=lupdos3cRet
            - PGDATABASE=test_db
            - POSTGRES_USER=lupdo
            - POSTGRES_PASSWORD=lupdos3cRet
            - POSTGRES_DB=test_db
        volumes:
            - ./src/__tests__/data/pg11.sql:/docker-entrypoint-initdb.d/init.sql

    waitpostgres12:
        image: postgis/postgis:12-3.3-alpine
        links:
            - postgres12
        depends_on:
            - postgres12
        entrypoint:
            - bash
            - -c
            - 'until /usr/local/bin/psql postgres://lupdo:lupdos3cRet@postgres12/test_db -c "SELECT 1"; do sleep 5; done'

    postgres13:
        image: postgis/postgis:13-3.3-alpine
        command: '-c full_page_writes=off -c fsync=off -c synchronous_commit=off'
        ports:
            - '25433:5432'
        environment:
            - PGUSER=ludpo
            - PGPASSWORD=lupdos3cRet
            - PGDATABASE=test_db
            - POSTGRES_USER=lupdo
            - POSTGRES_PASSWORD=lupdos3cRet
            - POSTGRES_DB=test_db
        volumes:
            - ./src/__tests__/data/pg13.sql:/docker-entrypoint-initdb.d/init.sql

    waitpostgres13:
        image: postgis/postgis:13-3.3-alpine
        links:
            - postgres13
        depends_on:
            - postgres13
        entrypoint:
            - bash
            - -c
            - 'until /usr/local/bin/psql postgres://lupdo:lupdos3cRet@postgres13/test_db -c "SELECT 1"; do sleep 5; done'

    postgres14:
        image: postgis/postgis:14-3.3-alpine
        command: '-c full_page_writes=off -c fsync=off -c synchronous_commit=off'
        ports:
            - '25434:5432'
        environment:
            - PGUSER=ludpo
            - PGPASSWORD=lupdos3cRet
            - PGDATABASE=test_db
            - POSTGRES_USER=lupdo
            - POSTGRES_PASSWORD=lupdos3cRet
            - POSTGRES_DB=test_db
        volumes:
            - ./src/__tests__/data/pg13.sql:/docker-entrypoint-initdb.d/init.sql

    waitpostgres14:
        image: postgis/postgis:14-3.3-alpine
        links:
            - postgres14
        depends_on:
            - postgres14
        entrypoint:
            - bash
            - -c
            - 'until /usr/local/bin/psql postgres://lupdo:lupdos3cRet@postgres14/test_db -c "SELECT 1"; do sleep 5; done'

    postgres15:
        image: postgis/postgis:15-3.3-alpine
        command: '-c full_page_writes=off -c fsync=off -c synchronous_commit=off'
        ports:
            - '25435:5432'
        environment:
            - PGUSER=ludpo
            - PGPASSWORD=lupdos3cRet
            - PGDATABASE=test_db
            - POSTGRES_USER=lupdo
            - POSTGRES_PASSWORD=lupdos3cRet
            - POSTGRES_DB=test_db
        volumes:
            - ./src/__tests__/data/pg13.sql:/docker-entrypoint-initdb.d/init.sql

    waitpostgres15:
        image: postgis/postgis:15-3.3-alpine
        links:
            - postgres15
        depends_on:
            - postgres15
        entrypoint:
            - bash
            - -c
            - 'until /usr/local/bin/psql postgres://lupdo:lupdos3cRet@postgres15/test_db -c "SELECT 1"; do sleep 5; done'
