services:

  crdb231:
    ports:
      - "26257:26257"
  waitcrdb231:
    image: cockroachdb/cockroach:latest-v23.1
    links:
      - crdb231
    depends_on:
      - crdb231
    environment:
      - COCKROACH_DATABASE=test_db
      - COCKROACH_USER=lupdo
      - COCKROACH_HOST=crdb231
      - COCKROACH_INSECURE=true
    entrypoint:
      - bash
      - -c
      - 'until cockroach sql --execute "SELECT 1"; do sleep 5; done'

  crdb232:
    ports:
      - "26257:26257"
  waitcrdb232:
    image: cockroachdb/cockroach:latest-v23.2
    links:
      - crdb232
    depends_on:
      - crdb232
    environment:
      - COCKROACH_DATABASE=test_db
      - COCKROACH_USER=lupdo
      - COCKROACH_HOST=crdb232
      - COCKROACH_INSECURE=true
    entrypoint:
      - bash
      - -c
      - 'until cockroach sql --execute "SELECT 1"; do sleep 5; done'

  crdb241:
    ports:
      - "26257:26257"
  waitcrdb241:
    image: cockroachdb/cockroach:latest-v24.1
    links:
      - crdb241
    depends_on:
      - crdb241
    environment:
      - COCKROACH_DATABASE=test_db
      - COCKROACH_USER=lupdo
      - COCKROACH_HOST=crdb241
      - COCKROACH_INSECURE=true
    entrypoint:
      - bash
      - -c
      - 'until cockroach sql --execute "SELECT 1"; do sleep 5; done'

  crdb242:
    ports:
      - "26257:26257"
  waitcrdb242:
    image: cockroachdb/cockroach:latest-v24.2
    links:
      - crdb242
    depends_on:
      - crdb242
    environment:
      - COCKROACH_DATABASE=test_db
      - COCKROACH_USER=lupdo
      - COCKROACH_HOST=crdb242
      - COCKROACH_INSECURE=true
    entrypoint:
      - bash
      - -c
      - 'until cockroach sql --execute "SELECT 1"; do sleep 5; done'

  postgres12:
    ports:
      - '5432:5432'
  waitpostgres12:
    image: postgis/postgis:12-3.4-alpine
    links:
      - postgres12
    depends_on:
      - postgres12
    entrypoint:
      - bash
      - -c
      - 'until /usr/local/bin/psql postgres://lupdo:lupdos3cRet@postgres12/test_db -c "SELECT 1"; do sleep 5; done'

  postgres13:
    ports:
      - '5432:5432'
  waitpostgres13:
    image: postgis/postgis:13-3.4-alpine
    links:
      - postgres13
    depends_on:
      - postgres13
    entrypoint:
      - bash
      - -c
      - 'until /usr/local/bin/psql postgres://lupdo:lupdos3cRet@postgres13/test_db -c "SELECT 1"; do sleep 5; done'

  postgres14:
    ports:
      - '5432:5432'
  waitpostgres14:
    image: postgis/postgis:14-3.4-alpine
    links:
      - postgres14
    depends_on:
      - postgres14
    entrypoint:
      - bash
      - -c
      - 'until /usr/local/bin/psql postgres://lupdo:lupdos3cRet@postgres14/test_db -c "SELECT 1"; do sleep 5; done'

  postgres15:
    ports:
      - '5432:5432'
  waitpostgres15:
    image: postgis/postgis:15-3.4-alpine
    links:
      - postgres15
    depends_on:
      - postgres15
    entrypoint:
      - bash
      - -c
      - 'until /usr/local/bin/psql postgres://lupdo:lupdos3cRet@postgres15/test_db -c "SELECT 1"; do sleep 5; done'

  postgres16:
    ports:
      - '5432:5432'
  waitpostgres16:
    image: postgis/postgis:16-3.4-alpine
    links:
      - postgres16
    depends_on:
      - postgres16
    entrypoint:
      - bash
      - -c
      - 'until /usr/local/bin/psql postgres://lupdo:lupdos3cRet@postgres16/test_db -c "SELECT 1"; do sleep 5; done'
