name: Coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Start Database(s)
        run: |
          docker compose \
            --file ".devcontainer/docker-compose.yml" \
            --file ".devcontainer/docker-compose-ci.yml" \
            up \
              --detach \
              --build \
              "postgres16"

      - name: Run npm install
        run: npm ci

      - name: Initialize Database
        run: |
          docker compose \
            --file ".devcontainer/docker-compose.yml" \
            --file ".devcontainer/docker-compose-ci.yml" \
            up \
              "waitpostgres16"

      - name: Coverage
        run: npm run test:coverage
        env:
          CI: true
          DB: postgres16

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: false
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: console
          thresholds: '75 90'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Stop Database(s)
        run: |
          docker compose \
            --file ".devcontainer/docker-compose.yml" \
            --file ".devcontainer/docker-compose-ci.yml" \
            down
